name: PROD

on:
  push:
    # branches:
    #   - main
    paths-ignore:
      - "README.md"
      - "assets/*"
    tags:
      - 'prod-*'

env:
  DEPLOY_STAGE: prod
  WORKING_CODE_REPO: ${{ github.event.repository.name }}
  WRANGLER_VERSION: '4.10.0'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    name: Deploy to cf worker
    steps:
      - uses: actions/checkout@v3
      
      - name: set node version according to .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      
      - name: Deploy using Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: ${{ env.WRANGLER_VERSION }}
          preCommands: npm ci
          command: deploy --env prod
          environment: prod
          secrets: |
            API_ACCESS_TOKEN_WORKER
            TELEGRAM_BOT_TOKEN
            TELEGRAM_CHAT_ID
            TAILNET_NAME
            TAILSCALE_OAUTH_CLIENT_ID
            TAILSCALE_OAUTH_CLIENT_SECRET
            DOWN_THRESHOLD_MINUTES
            REMINDER_INTERVAL_MINUTES
            MONITOR_TAGS
            TOKEN_KV_KEY
            TOKEN_EXPIRY_BUFFER_SECONDS
        env:
          API_ACCESS_TOKEN_WORKER: ${{ env.API_ACCESS_TOKEN_WORKER }}
          TELEGRAM_BOT_TOKEN: ${{ env.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ env.TELEGRAM_CHAT_ID }}
          TAILNET_NAME: ${{ env.TAILNET_NAME }}
          TAILSCALE_OAUTH_CLIENT_ID: ${{ env.TAILSCALE_OAUTH_CLIENT_ID }}
          TAILSCALE_OAUTH_CLIENT_SECRET: ${{ env.TAILSCALE_OAUTH_CLIENT_SECRET }}
          DOWN_THRESHOLD_MINUTES: ${{ env.DOWN_THRESHOLD_MINUTES }}
          REMINDER_INTERVAL_MINUTES: ${{ env.REMINDER_INTERVAL_MINUTES }}
          MONITOR_TAGS: ${{ env.MONITOR_TAGS }}
          TOKEN_KV_KEY: ${{ env.TOKEN_KV_KEY }}
          TOKEN_EXPIRY_BUFFER_SECONDS: ${{ env.TOKEN_EXPIRY_BUFFER_SECONDS }}
